# Generated by Django 4.2.7 on 2025-10-28 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, db_index=True, help_text='匿名用户会话ID', max_length=255, null=True)),
                ('provider', models.CharField(help_text='模型提供商: gpt, claude, qwen, doubao, gemini', max_length=50)),
                ('model_name', models.CharField(help_text='具体模型名称: gpt-4o, claude-3-5-sonnet等', max_length=100)),
                ('api_key', models.CharField(blank=True, help_text='API密钥', max_length=500)),
                ('api_base', models.CharField(blank=True, help_text='API基础URL', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='是否为当前激活的模型')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_model_config',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='ai_model_co_user_id_ed51cc_idx'), models.Index(fields=['session_id', 'is_active'], name='ai_model_co_session_d1cfcc_idx')],
            },
        ),
    ]
