# Generated by Django 4.2.7 on 2025-10-29 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_aimodelconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, db_index=True, help_text='匿名用户会话ID', max_length=255, null=True)),
                ('title', models.CharField(help_text='会话标题（文章标题或自定义）', max_length=500)),
                ('paper_title', models.CharField(blank=True, help_text='关联的论文标题', max_length=1000)),
                ('paper_url', models.URLField(blank=True, help_text='论文URL')),
                ('session_type', models.CharField(choices=[('translate', '翻译'), ('chat', '对话'), ('mixed', '混合')], default='mixed', help_text='会话类型', max_length=20)),
                ('ai_provider', models.CharField(blank=True, help_text='使用的AI提供商', max_length=50)),
                ('ai_model', models.CharField(blank=True, help_text='使用的AI模型', max_length=100)),
                ('context_text', models.TextField(blank=True, help_text='选中的上下文文本')),
                ('message_count', models.IntegerField(default=0, help_text='消息数量')),
                ('last_message_at', models.DateTimeField(blank=True, help_text='最后消息时间', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='是否活跃')),
                ('is_pinned', models.BooleanField(default=False, help_text='是否置顶')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_session',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', 'AI助手'), ('system', '系统')], help_text='消息角色', max_length=20)),
                ('content', models.TextField(help_text='消息内容')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='消息元数据（如token数、耗时等）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.chatsession')),
            ],
            options={
                'db_table': 'chat_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', 'is_active'], name='chat_sessio_user_id_5cf35d_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['session_id', 'is_active'], name='chat_sessio_session_2ff1b5_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['-last_message_at'], name='chat_sessio_last_me_4f664a_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='chat_messag_session_4940cf_idx'),
        ),
    ]
